server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB

pozarreal:
  datasourceUrl: jdbc:ucanaccess://PATH_TO_DB;password=${POZARREAL_DB_PWD}
  fees:
    biMonthlyMaintenanceFee: 800
    yearlyMaintenanceFee: 4560
    parkingPenFee: 1500

dropbox:
  accessToken: ${DROPBOX_ACCESS_TOKEN}
  clientIdentifier: ${DROPBOX_CLIENT_IDENTIFIER:'pozarreal'}